"""create songs table

Revision ID: 08ccbed85f79
Revises:
Create Date: 2024-10-19 22:24:24.562059

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "08ccbed85f79"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "songs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False
        ),
        sa.Column("danceability", sa.Numeric(precision=5, scale=3), nullable=False),
        sa.Column("energy", sa.Numeric(precision=5, scale=3), nullable=False),
        sa.Column("mode", sa.Enum("off", "on", name="modeenum"), nullable=True),
        sa.Column("acousticness", sa.Numeric(precision=10, scale=10), nullable=False),
        sa.Column("tempo", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("num_sections", sa.Integer(), nullable=False),
        sa.Column("num_segments", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("soft_delete", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_songs_id"), "songs", ["id"], unique=False)
    op.create_index(op.f("ix_songs_playlist_id"), "songs", ["playlist_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_songs_playlist_id"), table_name="songs")
    op.drop_index(op.f("ix_songs_id"), table_name="songs")
    op.drop_table("songs")
    # ### end Alembic commands ###
